### ISSUE TITLE
make test fails: Error from server (NotFound): pods "testpod" not found

### ISSUE THREAD

**Issue by Sponge-Bas** [canonical/spark-rock#64] opened 2024-01-02 16:46 UTC
When running the spark validation (test run https://solutions.qa.canonical.com/testruns/80da8e6c-1e83-4992-8e5b-6b769ee5d4c3/), the execution of `make test` fails with:

```
...
##################################
RUN EXAMPLE JOB
##################################
setup_user() spark tests 
namespace/tests created
pod "testpod" deleted
cleanup_user_failure()......
namespace "tests" deleted
error: unable to upgrade connection: container not found ("spark")
error: unable to upgrade connection: container not found ("spark")
error: unable to upgrade connection: container not found ("spark")
error: unable to upgrade connection: container not found ("spark")
error: unable to upgrade connection: container not found ("spark")
error: unable to upgrade connection: container not found ("spark")
Error from server (NotFound): pods "testpod" not found
Error from server (NotFound): pods "testpod" not found
make: *** [Makefile:111: tests] Error 1

2023-12-17-10:31:38 root ERROR 2[localhost] STDERR follows:
ERROR the following task failed:
 - id "238" with return code 2

use 'juju show-task' to inspect the failure


Traceback (most recent call last):
  File "/usr/local/bin/fce", line 33, in <module>
    sys.exit(load_entry_point('foundationcloudengine', 'console_scripts', 'fce')())
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 217, in entry_point
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/main.py", line 208, in main
    opts.func(opts)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/command.py", line 91, in run
    self.run_per_layer(layer, args)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/commands/validate.py", line 23, in run_per_layer
    layer.validate(tests=args.validators)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 280, in validate
    ran_validator = self.validate_inner(*args, **kwargs)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 265, in validate_inner
    validator.run()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/baselayer.py", line 524, in run
    self.run_inner()
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/sparklayer.py", line 330, in run_inner
    self.run_tests(model)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/sparklayer.py", line 342, in run_tests
    exec_and_log(
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/layers/snappedjujuworkloadlayer.py", line 23, in exec_and_log
    logger.info(juju_exec(model_name, unit, cmd))
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/juju_cli.py", line 403, in juju_exec
    return local(command)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 278, in local
    return run_cmd(cmd, target_machine, **kwargs)
  File "/home/ubuntu/cpe/foundation/foundationcloudengine/foundationcloudengine/remotehelpers.py", line 209, in run_cmd
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['juju', 'exec', '-m', 'snapped-microk8s', '-u', 'microk8s/0', '--wait', '14400s', 'cd /home/ubuntu/charmed-spark-rock&& runuser -u ubuntu -- make tests']' returned non-zero exit status 1.
```

The entire log of this executing can be found [here](https://oil-jenkins.canonical.com/artifacts/80da8e6c-1e83-4992-8e5b-6b769ee5d4c3/fce_validate_248/fce_validate_248_spark_spark-integration_console.out).

I haven't located the cause of this issue yet.

**Comment by Sponge-Bas** [comment] 2024-01-02 16:46
Tagging @kaskavel since he has been working on the implementation in our lab

**Comment by deusebio** [comment] 2024-09-12 15:30
@Sponge-Bas I did sync with kosta to make sure that the Spark test were working. Probably we then didn't close this ticket. I'll do so now, but feel free to re-open if the problem is still there.

**Closed as completed by deusebio** 2024-09-12 15:30 UTC
